### ISSUE TITLE
Powering the T-CAN485

### ISSUE THREAD

**Issue by laurencei** [Elwell/pool-heatpump#1]
Hi mate,

Thanks for this info. I've been reading across a bunch of forum threads. I've got the Madimack Elite v3 pool heater. It's the exact same board as a few others in the posts.

I've ordered the T-CAN485, same as you.

One question I wanted to double check - how are you powering the board? Are you just using the 12v + gnd from the RS485 port to the power port of the T-CAN485, then sending data into the other side of the board?

**Comment by Elwell** [comment]
Yes, exactly that. For testing I also have one of those dc socket to
terminal adaptors wired in too, so I can unplug the device from heatpump to
power / flash / test on bench and then take it back outside.

For now it's attached with a plastic bag round the cable (ahem, not good I
know) as my plan is to design a new PCB that fits back inside the original
'wifi adaptor' case but has ESP32 + RS485 interface, button (to match the
position of the case) and status LED

**Comment by Elwell** [comment]
One other thing that's not documented yet - it looks like the control board on the heatpump can either run a PWM DC fan (side connector) OR have a Low/Med/High speed set via the relays on the top edge. Ours is the latter sort, so fan speed always shows 0, but I see digout 3/4/5 coming on for fast/med/slow. I haven't yet combined these into a pretty unified "AC Fan Speed" single sensor yet.
